-- MySQL Script generated by MySQL Workbench
-- Mon Feb 17 22:54:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Fornisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornisseur` (
  `idFornisseur` INT NOT NULL,
  `Nom-Fornisseur` TEXT(50) NOT NULL,
  `Email_fr` TEXT(50) NOT NULL,
  `Telephone` TEXT(50) NOT NULL,
  PRIMARY KEY (`idFornisseur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Achats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Achats` (
  `idAchats` INT NOT NULL,
  `Date_achat` DATE NOT NULL,
  `Prix_achat` DECIMAL(10,2) NOT NULL,
  `Quantite` VARCHAR(45) NOT NULL,
  `Montant_TTC` DECIMAL(10,2) NULL,
  `Fornisseur_idFornisseur` INT NOT NULL,
  PRIMARY KEY (`idAchats`),
  INDEX `fk_Achats_Fornisseur1_idx` (`Fornisseur_idFornisseur` ASC) VISIBLE,
  CONSTRAINT `fk_Achats_Fornisseur1`
    FOREIGN KEY (`Fornisseur_idFornisseur`)
    REFERENCES `mydb`.`Fornisseur` (`idFornisseur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produits` (
  `idProduits` INT NULL AUTO_INCREMENT,
  `IDCategorie` VARCHAR(50) NOT NULL,
  `Code_barre` TEXT(50) NOT NULL,
  `Designation` TEXT(50) NOT NULL,
  `Prix_achat` DECIMAL(10,2) NOT NULL,
  `Prix_vente` DECIMAL(10,2) NOT NULL,
  `Stock` INT NOT NULL,
  `Photo` VARCHAR(45) NOT NULL,
  `Achats_idAchats` INT NOT NULL,
  PRIMARY KEY (`idProduits`),
  INDEX `fk_Produits_Achats1_idx` (`Achats_idAchats` ASC) VISIBLE,
  CONSTRAINT `fk_Produits_Achats1`
    FOREIGN KEY (`Achats_idAchats`)
    REFERENCES `mydb`.`Achats` (`idAchats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categories` (
  `idCategories` INT NULL,
  `Designation` VARCHAR(100) NOT NULL,
  `Produits_idProduits` INT NOT NULL,
  PRIMARY KEY (`idCategories`),
  INDEX `fk_Categories_Produits1_idx` (`Produits_idProduits` ASC) VISIBLE,
  CONSTRAINT `fk_Categories_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `mydb`.`Produits` (`idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categories_has_Produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categories_has_Produits` (
  `Categories_idCategories` INT NOT NULL,
  `Produits_idProduits` INT NOT NULL,
  PRIMARY KEY (`Categories_idCategories`, `Produits_idProduits`),
  INDEX `fk_Categories_has_Produits_Produits1_idx` (`Produits_idProduits` ASC) VISIBLE,
  INDEX `fk_Categories_has_Produits_Categories_idx` (`Categories_idCategories` ASC) VISIBLE,
  CONSTRAINT `fk_Categories_has_Produits_Categories`
    FOREIGN KEY (`Categories_idCategories`)
    REFERENCES `mydb`.`Categories` (`idCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categories_has_Produits_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `mydb`.`Produits` (`idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Facture` (
  `idFacture` INT NULL,
  `Date_Facture` DATETIME NULL,
  `Quantite` VARCHAR(45) NOT NULL,
  `Montant_TTC` DECIMAL(10,2) NULL,
  `Total` DECIMAL(10,2) NOT NULL,
  `Num_Facture` VARCHAR(45) NULL,
  PRIMARY KEY (`idFacture`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventes` (
  `idVentes` INT NULL,
  `Date_vente` DATE NOT NULL,
  `IDClient` VARCHAR(45) NOT NULL,
  `Quantite` INT NOT NULL,
  `Prix_vente` DECIMAL NOT NULL,
  `Montant_TTC` DECIMAL NOT NULL,
  `Produits_idProduits` INT NOT NULL,
  `Facture_idFacture` INT NOT NULL,
  PRIMARY KEY (`idVentes`),
  INDEX `fk_Ventes_Produits1_idx` (`Produits_idProduits` ASC) VISIBLE,
  INDEX `fk_Ventes_Facture1_idx` (`Facture_idFacture` ASC) VISIBLE,
  CONSTRAINT `fk_Ventes_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `mydb`.`Produits` (`idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventes_Facture1`
    FOREIGN KEY (`Facture_idFacture`)
    REFERENCES `mydb`.`Facture` (`idFacture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `idClients` INT NULL,
  `Nom_Client` TEXT(50) NOT NULL,
  `Telephone` TEXT(50) NULL,
  `Email` TEXT(50) NULL,
  `Cin` TEXT(15) NOT NULL,
  `Adress` TEXT(50) NULL,
  `Ventes_idVentes` INT NOT NULL,
  PRIMARY KEY (`idClients`),
  INDEX `fk_Clients_Ventes1_idx` (`Ventes_idVentes` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_Ventes1`
    FOREIGN KEY (`Ventes_idVentes`)
    REFERENCES `mydb`.`Ventes` (`idVentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paiemant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paiemant` (
  `idPaiemant` INT NULL,
  `Date_Paiement` DATE NULL,
  `Mode_payer` VARCHAR(45) NULL,
  `Montant_TTC` DECIMAL(10,2) NOT NULL,
  `Facture_idFacture` INT NOT NULL,
  PRIMARY KEY (`idPaiemant`),
  INDEX `fk_Paiemant_Facture1_idx` (`Facture_idFacture` ASC) VISIBLE,
  CONSTRAINT `fk_Paiemant_Facture1`
    FOREIGN KEY (`Facture_idFacture`)
    REFERENCES `mydb`.`Facture` (`idFacture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
